
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CineplexCustomerWebsite.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Seating
{

    public Seating()
    {

        this.SessionBooking = new HashSet<SessionBooking>();

    }


    public int SeatingID { get; set; }

    public string Row { get; set; }

    public int SeatNumber { get; set; }

    public int SessionID { get; set; }

    public bool IsTaken { get; set; }



    public virtual MovieSession MovieSession { get; set; }

    public virtual ICollection<SessionBooking> SessionBooking { get; set; }

}

}
