
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CineplexCustomerWebsite.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SessionBooking
{

    public SessionBooking()
    {

        this.Seating = new HashSet<Seating>();

    }


    public int BookingID { get; set; }

    public int SessionID { get; set; }

    public string UserEmail { get; set; }



    public virtual ICollection<Seating> Seating { get; set; }

    public virtual MovieSession MovieSession { get; set; }

}

}
