//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatA
    {
        public int ID { get; set; }
        public string RowID { get; set; }
        public int SeatNumber { get; set; }
        public int SessionID { get; set; }
        public Nullable<bool> isTaken { get; set; }
    }
}
