//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionBooking
    {
        public int BookingID { get; set; }
        public int SessionID { get; set; }
        public string UserEmail { get; set; }
        public int CineplexID { get; set; }
        public int SeatingID { get; set; }
    
        public virtual MovieSession MovieSession { get; set; }
        public virtual Seating Seating { get; set; }
    }
}
